# Generated by Django 5.0.7 on 2024-07-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='default_slug', unique=True),
            preserve_default=False,
        ),
    ]
